指令: team
未加入隊伍系統表單標題: 隊伍系統
未加入隊伍系統表單查看可加入隊伍按鈕: 查看可加入隊伍
未加入隊伍系統表單創建新隊伍按鈕: 創建新隊伍
創建隊伍表單標題: 創建隊伍
創建隊伍表單輸入提示: 請輸入隊伍名稱
伺服器所有可加入隊伍表單標題: 伺服器所有可加入隊伍
伺服器所有可加入隊伍表單提示: 點擊傳送請求給隊伍
退出隊伍表單標題: 退出隊伍
退出隊伍表單退出按鈕: 退出隊伍
隊伍系統表單標題: 隊伍系統
隊伍系統查看隊伍人數按鈕: 查看隊伍人數
隊伍系統退出隊伍按鈕: 退出隊伍
隊長查看隊伍邀請按鈕: 查看隊伍邀請
隊長踢出成員按鈕: 踢出成員
成員名單: 成員名單@a隊伍
隊長邀請函標題: 邀請函
隊長踢出玩家表單標題: 踢出玩家
玩家發送申請給隊伍: 你已發送請求給隊伍@a
隊長收到訊邀請訊息通知: 隊伍通知你已經收到來自@p的請求
加入隊伍玩家發送訊息: 恭喜加入到@a隊伍裡悠
其餘玩家發送加入訊息: 歡迎新人@p進入了隊伍
退出隊伍玩家發送訊息: 你已經退出隊伍瞜
退出隊伍訊息: 玩家@p已經退出@a搂
隊長設定隊伍功能按鈕: 隊伍設定
隊伍設置表單標題: 隊伍設定